name: airflow

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy
  networks:
    - dag-sample
    - bionicpro-net
  environment: &airflow-common-env
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW_CONN_WRITE_TO_POSTGRES: 'postgres://airflow:airflow@postgres:5432/bionicpro'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW_INPUT_DIR: '/opt/airflow/dag-inputs'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'your_airflow_webserver_sec_key'
    _PIP_ADDITIONAL_REQUIREMENTS: 'psycopg2-binary clickhouse-connect'
  volumes:
    - './dags:/opt/airflow/dags'
    - './requirements.txt:/opt/airflow/requirements.txt'
    - './data:/opt/airflow/sample_files'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - dag-sample
      - bionicpro-net
    volumes:
      - './db/init-db.sql:/docker-entrypoint-initdb.d/db.sql'
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks:
      - dag-sample
      - bionicpro-net
    ports:
      - "8090:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-webserver:
        condition: service_healthy
    networks:
      - dag-sample
      - bionicpro-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-triggerer:
    <<: *airflow-common
    restart: unless-stopped
    command: bash -c "airflow triggerer"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks:
      - dag-sample
      - bionicpro-net
    healthcheck:
      test: [ "CMD-SHELL", "airflow", "jobs", "check", "--job-type", "TriggererJob", "--hostname", "\"${HOSTNAME}\"" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  airflow-cli:
    <<: *airflow-common
    command: bash -c airflow
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dag-sample
      - bionicpro-net
    profiles:
      - debug

  airflow-init:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "airflow db init && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@sample.ru --password admin"
    networks:
      - dag-sample
      - bionicpro-net

networks:
  dag-sample:
    name: dag-sample
    driver: bridge

  bionicpro-net:
    external: true
