[server.http]
address = "0.0.0.0:8000"

[server.logger]
level = "info"

[server.login]
cors = ["*"]

[server.login.keycloak]
url = "http://localhost:8080"
realm = "reports-realm"

[server.login.jwt_cache]
expired = "15m"

[reporter]
address = "localhost:9000"
database = "analytic"
username = "analytic_user"
password = "analytic_password"
